name: celestia-daily # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.+git' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: celestia
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

architectures: #build Architectures
   - build-on: amd64 
   - build-on: i386
   - build-on: arm64
   
apps:
  celestia:
    command: desktop-launch $SNAP/usr/bin/celestia
    #common-id: 
    plugs: [desktop, wayland, x11, unity7, gsettings, opengl, network, network-bind, audio-playback, home, raw-usb]
    
parts:
  celestia:
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
    source: https://github.com/CelestiaProject/Celestia.git
    source-type: git
    source-depth : 1
    
    organize:
      snap/celestia-daily/current/usr: usr
    parse-info: [usr/share/metainfo/celestia.appdata.xml] #appstream info
    after : [desktop-celestia]
    
    build-packages:
      - build-essential
      - doxygen
      - gettext
      - libepoxy-dev
      - libjpeg-dev
      - libpng-dev
      - libtheora-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libeigen3-dev
      - libfmt-dev
      - qtbase5-dev
      - qtbase5-dev-tools 
      - libqt5opengl5-dev
      - liblua5.3-dev
      
    #stage-packages:
      
      
  desktop-celestia:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    source-depth : 1
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
    - build-essential
    - qtbase5-dev
    - dpkg-dev
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgdk-pixbuf2.0-0
    - libqt5svg5 # for loading icon themes which are svg
    - try: [appmenu-qt5] # not available on core18
    - locales-all
    - xdg-user-dirs
    - fcitx-frontend-qt5
    - libgtk2.0-0
    
  qt5-gtk-platform:
    plugin: nil
    stage-packages:
      - qt5-gtk-platformtheme

plugs:
  # Support for common GTK themes
  # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
